### ISSUE TITLE
Tag a release.

### ISSUE THREAD

**Issue by shaggytwodope** [in0rdr/diary#11]
I'd like to know if things matured enough to consider tagging a release. If not what goals are in mind before doing so?

**Comment by in0rdr** [comment]
Sure, very soon.

I really want to have a 'd' option to remove entries, so add/remove is a complete feature set. Then I think we can tag this 'zerosomething' dispite the few bugs still floating around.

What do you think?

**Comment by shaggytwodope** [comment]
0.1 and so on would be nice til stable. At least makes sense in my head that way.

**Comment by in0rdr** [comment]
Ok, I just tagged the current state as [v0.1](https://github.com/in0rdr/diary/releases/tag/v0.1), unstable.

Thanks

**Comment by shaggytwodope** [comment]
@in0rdr So I added to the aur, and made a ppa package for it.

https://aur.archlinux.org/packages/diary/

https://launchpad.net/~twodopeshaggy/+archive/ubuntu/ppapackages

**Comment by in0rdr** [comment]
Thank you very much!
