### ISSUE TITLE
Feature Request: Shortcuts to jump to next/prev diary entry

### ISSUE THREAD

**Issue by mbjd** [in0rdr/diary#14]
It would be neat if we could (for example) have `n`/`N` jump to the next/previous diary entry so you can easily skip over 'empty' days in the calendar.

I'm not sure about an efficient implementation, a brute-force way could be to just traverse the dates and stop at the first one where there is a diary file.

Something more elegant would be a doubly linked list of dates, where the elements are the dates with an entry. Jumping would obviously be very cheap as you just have to follow one pointer. You could build the whole list at startup, and then after editing a field only check if a file has been added/removed at that exact spot. If so, you can just save that change in the linked list very efficiently.

I'm probably going to try to do this too if I find time, so don't consider this a top priority if you don't feel like doing it right now

**Comment by in0rdr** [comment]
Thanks for this good suggestion, I like it very much.

Would be great if you can find time to look into this. For the implementation I think the greedy aproach will do. I personally think that diary entries will not be apart more than a month or so. This is why I would prefer the greedy approach for a first try. If we feel fancy we can always improve with a linked list.

Your thinking is very much appreciated!

**Comment by livibetter** [comment]
There is one problem with brute-force/greedy that I can think of, if there is no more entries after the date and you press <kbd>n</kbd> (or before and <kbd>N</kbd>), endless loop?

The current `draw_calender` would go through each date on screen to check. I don't have much dealing with filesystem, but would `glob(3)` be a better approach?

It returns a list of matched filenames, even with a 10-year-dedicated diary, that would be just 365*10 (give 1 or 2 extra) files, 13\*365=4745 bytes, I think. There is even a matched count.

It certainly would require less calls, such as `access(2)`. Only need to check if the dates on screen are in that filename list. And when <kbd>n</kbd> is pressed, do string comparison with current date string to find the next date.

Of course, checks on matched filename might be required just to be safe.

**Comment by in0rdr** [comment]
`glob(3)` sounds like a very reasonable approach to me, thanks! You are right about the endless loop, it would not work that way.

**Comment by mbjd** [comment]
I've made a pull request implementing this feature: #37
