### ISSUE TITLE
Ask for confirmation before deleting journal entry.

### ISSUE THREAD

**Issue by ryanbahneman** [in0rdr/diary#16]
It's too easy to accidentally delete an entry and no way to recover the deleted entry.

It would be great to ask for confirmation before deleting an entry so that entries are not accidentally deleted.

**Comment by in0rdr** [comment]
You are absolutely right. I [fixed](https://github.com/in0rdr/diary/commit/d0b2143245e914ab3c04222ad62bc753bccc3e04) this with a confirmation question in the header.

Would be nice to have the escape key cancel the confirmation. Do you know how to do this?

Thanks

**Comment by shaggytwodope** [comment]
@in0rdr https://github.com/in0rdr/diary/pull/17

**Comment by in0rdr** [comment]
Thank you!
