### ISSUE TITLE
Highlight current day

### ISSUE THREAD

**Issue by in0rdr** [in0rdr/diary#2]

**Comment by SanketDG** [comment]
Hi, I was trying this out.

Looks like this should be done in the `draw_calender()` but it is only called one time, so the attribute settings go away when `prefresh()` gets called..

Any ideas on how else can I implement this?

**Comment by in0rdr** [comment]
I think the problem is not the refresh, but rather the `chgat` which reapplies the formatting every time `go_to()` is called. See [here](https://github.com/in0rdr/diary/blob/master/diary.c#L125), in the master branch where the whole line of the old cursor position is just formatted as `A_NORMAL`.

This would need to be changed into something similar as [here](https://github.com/in0rdr/diary/blob/feature/highlight/diary.c#L155) in the feature/hightlight branch. There I check if the old cursor position had an existing entry. If so I reapplied the underline.

In your implementation before you make the whole line as `A_NORMAL` you need to check if the old cursor position was the current date, and if so reapply the hightlight (or underline, depending on your implementation).

Hope it helps. Thanks for digging in!

**Comment by ryanbahneman** [comment]
I got something working. See my changes here: #9
