### ISSUE TITLE
Fix fpath() rpath pointer issues

### ISSUE THREAD

**Issue by ryanbahneman** [in0rdr/diary#20]
The error checking in function fpath() is not written correctly.

The hint are these warnings generated when you compile:

`diary.c:248:15: warning: equality comparison result unused [-Wunused-comparison]
        rpath == NULL;
        ~~~~~~^~~~~~~
diary.c:248:15: note: use '=' to turn this equality comparison into an assignment
        rpath == NULL;`

---

In the fpath function, you're trying to set a variable to NULL with the comparison operator `==` . Take the warning's advice and change that to `=`.


That won't be enough though because `rpath` is passed by value, so any modification to `rpath` will only exist in the scope of the `fpath()` call.

This warning gives you that clue:

`diary.c:135:9: warning: comparison of array 'path' equal to a null pointer is always false [-Wtautological-pointer-compare]
    if (path == NULL) {`

You need to pass the pointer by reference. See:
http://stackoverflow.com/questions/16299394/c-assign-pointer-to-null

**Comment by in0rdr** [comment]
Thank you very much, you are right. I am just in the middle of changing this. It doesn't seem to work though. I changed the method header to accept a `char** rpath` which is the pointer to the pointer which points to the first character of the result path. Inside the function `fpath` I changed every occurance from `rpath` simply to `*rpath`, dereferenced once to pass to `strcpy` and friends, also it reads now `*rpath = NULL` which is exactly what I want.

But unfortunately now I get:
```
note: expected 'char **' but argument is of type 'char (*)[100]'
```

which is only a warning, but it crashes with segmentation fault. Do I need to change the method declaration from `char**` to include the length (100) somehow?

Thanks!

**Comment by ryanbahneman** [comment]
It seems like the address of `path` is not modifiable. You have to use a variable that can be modified.

This worked for me:

```
char path[100];
char * ppath = path;
fpath(dir, dir_size, date, &ppath, sizeof path);
```

**Comment by in0rdr** [comment]
Works perfectly, thanks!

**Comment by ryanbahneman** [comment]
I saw your commit. It looks good!

I noticed you forgot to update the check in the outer functions though. You're still checking
```
if (path == NULL) {
```
 but you should now be checking 
```
if (ppath == NULL) {
```
Is your compiler spitting out warnings about this?

I'm getting
```
diary.c:136:9: warning: comparison of array 'path' equal to a null pointer is always false [-Wtautological-pointer-compare]
    if (path == NULL) {
```

**Comment by in0rdr** [comment]
Thanks, did not notice. Fixed it.

> Is your compiler spitting out warnings about this?

No, it was not. Now I changed the gcc settings to display all warnings so I can see them.
