### ISSUE TITLE
Seg Fault after writing daily entry

### ISSUE THREAD

**Issue by ryanbahneman** [in0rdr/diary#24]
I updated today and then wrote and entry. Upon quitting vim, diary crashed.
Trying to open diary again shows the same crash.

Seems like it's crashing on today's date

```
Nov 31  1  2  3  4  5  6
     7  8  9 10 11 12 13
    14 15 16 17 18 19 20
    21 22 23 24 25 26 27
Dec 28 29 30  1  2  3  4
     5  6 zsh: segmentation fault  diary .
```

**Comment by in0rdr** [comment]
Very strange, I am sorry to say that I have no idea why this happens.. Also i cannot reproduce this somehow. I am also using vim, but with bash not zsh.

**Comment by in0rdr** [comment]
I just tested with zsh, on my system there seems to be no problem

**Comment by ryanbahneman** [comment]
Thanks for checking. I'm closing this as it seems I had some stale output. I did a clean build and the problem went away.
