### ISSUE TITLE
Lack of UTF-8 chars in preview

### ISSUE THREAD

**Issue by mateossh** [in0rdr/diary#26]
Instead of letters I have weird spaces and tildes

![Proof here](https://cloud.githubusercontent.com/assets/17083034/21207772/683eefcc-c26a-11e6-848c-c74a8b78e8ed.png)

**Comment by shaggytwodope** [comment]
@mateossh can you share the exact text?

**Comment by shaggytwodope** [comment]
@in0rdr I made pr #27

I've tested with the following text:
`Text ð ñ ò ó ô õ ö ÷`
Before it only displayed
`Text`

Image cause it's pretty.
http://i.imgur.com/lLQ5YQ9.png
