### ISSUE TITLE
Trouble compiling on OSX

### ISSUE THREAD

**Issue by ryanbahneman** [in0rdr/diary#28]
When I compile on OSX, linking fails because ncursesw is not found.

For some reason OSX don't have ncursesw by default.

I can work around this installing ncurses with brew:

```bash
brew install homebrew/dupes/ncurses
```

and adding the linker argument

```
-L/usr/local/opt/ncurses/lib
```

Can you add something to README about this?

**Comment by klassegeljakt** [comment]
Compiling with -lncurses instead of -lncursesw should work on mac.

**Comment by shaggytwodope** [comment]
@ryanbahneman  I've opened pull request #29 to address this. From my understanding this should be all that's needed for now. However I would love feedback before @in0rdr merges as I do not own a mac machine. From my understanding however, the default ncurses on mac already supports the width character feature used to currently display UTF-8.
