### ISSUE TITLE
OSX _NL_TIME_* compilation issues

### ISSUE THREAD

**Issue by ryanbahneman** [in0rdr/diary#31]
I'm trying to compile and getting the following errors:

```
diary.c:306:51: error: use of undeclared identifier '_NL_TIME_WEEK_1STDAY'
        unsigned long d = (uintptr_t) nl_langinfo(_NL_TIME_WEEK_1STDAY);
                                                  ^
diary.c:317:54: error: use of undeclared identifier '_NL_TIME_FIRST_WEEKDAY'
        first_weekday = (base.tm_wday + *nl_langinfo(_NL_TIME_FIRST_WEEKDAY) - 1) % 7;
                                                     ^
```

I did some searching around, but couldn't find how to solve this correctly on OSX. If there is no easy fix, can we provide sane defaults?

**Comment by in0rdr** [comment]
#30 (which implements the change of the first day of the week depending on the locale) mentiones:
>this won't be portable if the system doesn't use glibc

Are you using glibc? I think we should check this in the code which library is in use, but I don't know how.

**Comment by shaggytwodope** [comment]
@ryanbahneman So I've tried to solve this. If you can clone/download from my [repo](https://github.com/shaggytwodope/diary). I'm not prepared to do a pull-request until this is confirmed working. And I fix the terrible commits lol. I'd like to know if it does compile and runs for you. And if possible post a screenshot.

@in0rdr Are you at all against using travis-ci? At the moment it does nothing more then run make on a linux and mac "vm" (in my repo). So at a minimum it'll inform if there are build failures running make.

**Comment by livibetter** [comment]
My bad, I have mentioned, but forgot to do the checking.

@in0rdr could you wrap a `#ifdef __GNU_LIBRARY__` around that piece of code. This would make sure without glibc, `first_weekday` is kept as Monday.

@shaggytwodope I would suggest using native OS X locale (which I don't know how), because just assuming the base date doesn't work (I only skimmed over the commits), you still doesn't know `_NL_TIME_FIRST_WEEKDAY`. If you find out how to work out natively on OS X, then adding a new check and setting the `first_weekday` accordingly.

**Comment by shaggytwodope** [comment]
@livibetter @ryanbahneman @in0rdr 
If you can take a look at this [commit](https://github.com/shaggytwodope/diary/commit/d6c7abfe1ecea627558908d5791ff6c9ea7df797). Understand that I'm self taught... so my c skills are moderate at best. But I think this is coming fairly close to native date. Altho This begins to limit portability for bsd. That is another weekend however. Anyway I'm tired today.. if you guys got any ideas or spot anything I did wrong lemme know.

**Comment by in0rdr** [comment]
@livibetter I wrapped the code block to check for glibc in [`7f2f926`](https://github.com/in0rdr/diary/commit/7f2f92642092512f0e296ea6daba7404f0af0a72)

@shaggytwodope I'm ready to work with travis-ci, this is a good idea. Also I had a look at your commits, thanks. I can confirm it works flawlessly on my linux box, but I do not know about OS X and BSD.. Just let me know when you are ready to merge your "portability changes" (with travis config). Thx!
