### ISSUE TITLE
YEAR_RANGE is quite short by default

### ISSUE THREAD

**Issue by bovine3dom** [in0rdr/diary#56]
https://github.com/in0rdr/diary/blob/3c2a58397740cb58bfbc4cae2ab0371bcf32a212/diary.h#L21

I find it confusing that the diary just stops at a year old - I always wonder what has happened to my old entries. Could it perhaps instead be set by default to 100 years? I don't anticipate needing more.

PS: I've apparently been using this program on-and-off for over four years now ... so thanks : )

**Comment by in0rdr** [comment]
I like your suggestion, but noticed that with 100 year range the program is too slow at startup. Can we fix it to 10y for the next release?

I hope that I can find time to implement a proper [config (ini) file](https://github.com/in0rdr/diary/issues/35) or so, to make this configurable..

**Comment by in0rdr** [comment]
@bovine3dom first draft for the config file is in https://github.com/in0rdr/diary/pull/61

**Comment by in0rdr** [comment]
The year range is now fully configurable through command line options or the optional config file, see [release 0.5](https://github.com/in0rdr/diary/releases/tag/v0.5).
