### ISSUE TITLE
Feature request: g/G to first/last non-empty entries

### ISSUE THREAD

**Issue by bovine3dom** [in0rdr/diary#57]
I'm not sure I can think of a reason why I would want to be able to jump immediately to today's date +/- YEAR_RANGE. Could they instead be bound to jumping to the first and last diary entries?

Somewhat related to #56 since with that g and G would make even less sense.

Sorry for the issue spam : )

**Comment by in0rdr** [comment]
Thanks a lot for your reports, they are very useful :)

I like that suggestion :+1:
