### ISSUE TITLE
AUR listing

### ISSUE THREAD

**Issue by bovine3dom** [in0rdr/diary#64]
This would simplify installation and discovery for Arch users.

It shouldn't be too difficult: https://wiki.archlinux.org/index.php/AUR_submission_guidelines

**Comment by in0rdr** [comment]
To search and discover the app, that would be useful indeed. @shaggytwodope maintained an AUR package in https://github.com/in0rdr/diary/issues/11#issuecomment-262696728. Maybe we can pick this up again?

For the purpose of installing signed packages from a trusted source, I put some effort into preparing packages on the Open Build Service (OBS): https://software.opensuse.org/download.html?project=home%3Ain0rdr&package=diary

The instructions for Arch are included as well. With help of the SUSE IRC channel I found out, that there appears to be an [issue with the `.zst` compression](https://github.com/openSUSE/software-o-o/issues/844#issuecomment-751922653) for these packages. Now that I've changed back to `.xz` packaging, the instructions show up again.

The public key is on [the keyservers](https://keyserver.ubuntu.com/pks/lookup?search=0x54A9D1F7050C44ED&fingerprint=on&op=index). According to the instructions in the wiki, the key should be [fetched once "pacman encounters a key it does not recognize"](https://wiki.archlinux.org/index.php/Pacman/Package_signing#Adding_developer_keys).

Intuitively, this does won't work with `SigLevel = Never`, which is suggested by the instructions on the OBS page for whatever reason..
