### ISSUE TITLE
n/N skip some entries

### ISSUE THREAD

**Issue by bovine3dom** [in0rdr/diary#67]
Seems to be approx 10% of entries. n and N skip a different set of entries.

I haven't had time to look at steps to reproduce this (and I'm not sure I will).

My entries are fairly sporadic rather than all bunched up.

**Comment by in0rdr** [comment]
Thanks for the report. Unfortunately I could not reproduce the issue (was using the `diary-nightly` build). I close the issue for now. Hope that is fine.
