### ISSUE TITLE
Arch repo from openSUSE has broken link

### ISSUE THREAD

**Issue by bovine3dom** [in0rdr/diary#69]
```
[I] ~ $ sudo pacman -Sy diary
:: Synchronising package databases...
 home_in0rdr_Arch is up to date
 core                         131.1 KiB  1351 KiB/s 00:00 [###############################] 100%
 extra                       1654.2 KiB  12.7 MiB/s 00:00 [###############################] 100%
 community                      5.4 MiB  67.8 MiB/s 00:00 [###############################] 100%
 multilib is up to date
resolving dependencies...
looking for conflicting packages...

Packages (1) diary-0.4-1

Total Download Size:   0.01 MiB
Total Installed Size:  0.03 MiB
Net Upgrade Size:      0.01 MiB

:: Proceed with installation? [Y/n] y
:: Retrieving packages...
error: failed retrieving file 'diary-0.4-1-x86_64.pkg.tar.xz' from download.opensuse.org : The requested URL returned error: 404
warning: failed to retrieve some files
error: failed to commit transaction (failed to retrieve some files)
Errors occurred, no packages were upgraded.
```

The big download button on the site works fine and points to `0.5.0` rather than `0.4.1`.

**Comment by in0rdr** [comment]
Thanks for the report. From a first look, seems related to https://github.com/openSUSE/open-build-service/issues/9953.

Did you try to [Force pacman to refresh the package lists](https://wiki.archlinux.org/index.php/Mirrors#Force_pacman_to_refresh_the_package_lists) with `pacman -Syy`?

**Comment by bovine3dom** [comment]
```
[I] ~ $ sudo pacman -Syy diary
[sudo] password for olie:
:: Synchronising package databases...
 home_in0rdr_Arch                                                                        935.0   B  0.00   B/s 00:00 [######################################################################] 100%
 core                                                                                    131.1 KiB  1311 KiB/s 00:00 [######################################################################] 100%
 extra                                                                                  1654.6 KiB  14.3 MiB/s 00:00 [######################################################################] 100%
 community                                                                                 5.4 MiB  67.8 MiB/s 00:00 [######################################################################] 100%
 multilib                                                                                151.5 KiB  0.00   B/s 00:00 [######################################################################] 100%
resolving dependencies...
looking for conflicting packages...

Packages (1) diary-0.4-1

Total Download Size:   0.01 MiB
Total Installed Size:  0.03 MiB
Net Upgrade Size:      0.01 MiB

:: Proceed with installation? [Y/n] y
:: Retrieving packages...
error: failed retrieving file 'diary-0.4-1-x86_64.pkg.tar.xz' from download.opensuse.org : The requested URL returned error: 404
warning: failed to retrieve some files
error: failed to commit transaction (failed to retrieve some files)
Errors occurred, no packages were upgraded.
```

Yes - no cigar.

**Comment by in0rdr** [comment]
I changed the sha256sums in the PKGBUILD in hindsight: https://build.opensuse.org/package/rdiff/home:in0rdr/diary?linkrev=base&rev=11

But it should have been rebuilt with the latest revision? :thinking: I did just trigger a "manual rebuild" operation. Let's see if that fixes the issue.

When I download the https://download.opensuse.org/repositories/home:/in0rdr/Arch/x86_64/home_in0rdr_Arch.db and extract it I can see the old diary version, as mentioned in the issue linked above..

**Comment by in0rdr** [comment]
did not help as far as I can tell, the database file still contains an old release..

**Comment by in0rdr** [comment]
An update here. I changed packages to [use `.xz` compression](https://build.opensuse.org/package/rdiff/home:in0rdr/diary?linkrev=base&rev=9) previously, because the nice [Arch logo button was not visible on the downloads page](https://software.opensuse.org/download.html?project=home%3Ain0rdr&package=diary). That fixed this issue :)

Now I [reverted back to the new default compression `.zst`](https://build.opensuse.org/package/rdiff/home:in0rdr/diary?linkrev=base&rev=13) just to see if everything works as expected in the mean time.

♻ building..

**Comment by in0rdr** [comment]
Did not show any effect

**Comment by in0rdr** [comment]
I tried a few things during some unnecessary [revisions](https://build.opensuse.org/package/revisions/home:in0rdr/diary) but figured that the upstream workaround does the job.

Could you please give that a try?
```bash
sed -i 's/download.opensuse.org/downloadcontent.opensuse.org/g' /etc/pacman.conf
pacman -Syu diary
```

**Comment by bovine3dom** [comment]
Works great now, have merged that PR. Thanks!
