### ISSUE TITLE
Invalid cursor move on macOS Monterey when holding down arrow down key 

### ISSUE THREAD

**Issue by JonnyBurger** [in0rdr/diary#81]
## Reproduction

1. Get a Mac
1. Open VSCode Terminal and start up diary
2. Hold <kbd>ArrownDown</kbd> until error appears

## Screenshot

![Kapture 2021-12-04 at 20 51 59](https://user-images.githubusercontent.com/1629785/144722826-ec86fcb9-080c-4d4e-8a11-0bcff0b654b5.gif)

**Comment by JonnyBurger** [comment]
1A support! 👍

**Comment by in0rdr** [comment]
Thanks for the help, there are many more of these. I use them during development:
https://github.com/in0rdr/diary/blob/master/docs/TESTING.md#send-stderr-to-file
